language: go

env:
  global:
    - CC_TEST_REPORTER_ID=43609087b6bca966af7bb9bd588db1f2b53676b04dabe082169920af27b2982f

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

  - go get -u github.com/golang/lint/golint

script:
  - ./gradlew --no-daemon -i build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
