language: go

env:
  global:
    - CC_TEST_REPORTER_ID=5075ccf1031ef51a0513d7610e5db799d62e8de4a8474e7196ea6991b4e1eaa0

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

  - go get -u github.com/golang/lint/golint

script:
  - ./gradlew --no-daemon -i build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
